apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: argoprojlabs/argocd-image-updater
    newTag: v0.9.0

resources:
  - https://github.com/argoproj-labs/argocd-image-updater/manifests/base/config?ref=v0.9.0
  - https://github.com/argoproj-labs/argocd-image-updater/manifests/base/deployment?ref=v0.9.0
  - https://github.com/argoproj-labs/argocd-image-updater/manifests/base/rbac?ref=v0.9.0
  - config/line-harbor-secret.yaml
patchesStrategicMerge:
  - config/argocd-image-updater-cm.yaml
