apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
data:
  log.level: trace
  registries.conf: |
    registries:
    - name: Line Harbor
      api_url: https://harbor.linecorp.com
      ping: no
      prefix: harbor.linecorp.com
      credentials: secret:argocd/line-harbor-secret#line.harbor.secret
  argocd.insecure: 'true'
  argocd.plaintext: 'false'
  argocd.grpc_web: 'false'
