apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-{{ .Values.app.phase }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: hello
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ks-yim/fluxcd-playground
    path: charts/hello
    targetRevision: HEAD
    helm:
      releaseName: hello-app-{{ .Values.app.phase }}
      valueFiles:
        - values.yaml
        - values-{{ .Values.app.phase }}.yaml
