apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: hello
    server: {{ .Values.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/ks-yim/fluxcd-playground
    path: charts/hello
    targetRevision: HEAD
    helm:
      releaseName: hello-app-{{ .Values.app.phase }}
      valueFiles:
        - values.yaml
        {{- if eq "alpha" .Values.app.phase }}
        - values-alpha.yaml
        {{- else if eq "beta" .Values.app.phase }}
        - values-beta.yaml
        {{- else if eq "staging" .Values.app.phase }}
        - values-staging.yaml
        {{- else if eq "release" .Values.app.phase }}
        - values-release.yaml
        {{- end }}
