{{- if eq .Values.app.phase "beta" }}
  {{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  {{- end }}
  {{- end }}
