apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: argoprojlabs/argocd-image-updater
    newTag: v0.9.0

resources:
  - install.yaml
  - config/line-harbor-secret.yaml
patchesStrategicMerge:
  - config/argocd-image-updater-cm.yaml
