apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/argocd
  - ../../base/argocd-image-updater
  - ../../base/app-of-apps

patchesStrategicMerge:
  - app-of-apps.yaml
