apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  channel.linecorp.com/phase: beta

resources:
  - ../../base/argocd
  - ../../base/argocd-image-updater
  - app-of-apps.yaml
