apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ks-yim/argocd-playground
    path: apps
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-alpha.yaml
